# modes/808_dial.py
# SAN3 Producer — 808 Dial Mode
# For: Hip Hop | RnB | Rap | Trap producers

from pathlib import Path

# All 12 notes with MIDI numbers (C4 = 60 standard / shown as C5 in FL Studio)
NOTE_MIDI = {
    "C": 60, "C#": 61, "D": 62, "D#": 63,
    "E": 64, "F":  65, "F#": 66, "G":  67,
    "G#": 68, "A": 69, "A#": 70, "B":  71,
}

# Frequency reference for tuning (Hz) — A4 = 440hz standard
NOTE_HZ = {
    "C":  261.63, "C#": 277.18, "D":  293.66, "D#": 311.13,
    "E":  329.63, "F":  349.23, "F#": 369.99, "G":  392.00,
    "G#": 415.30, "A":  440.00, "A#": 466.16, "B":  493.88,
}

# 808 problem diagnostics
PROBLEMS = {
    "1": "My 808 sounds weak / no boom",
    "2": "My 808 is muddy / too much bass",
    "3": "My 808 is clashing with the kick",
    "4": "My 808 sounds out of tune",
    "5": "My 808 disappears on small speakers",
    "6": "My 808 is too loud / distorting",
    "7": "All of the above / full chain",
}


def run(output_dir: Path) -> None:
    print("\n" + "="*52)
    print("  808 DIAL — SAN3 Co-Producer")
    print("  Hip Hop | RnB | Rap | Trap")
    print("="*52)

    # Get key
    print("\nWhat key is your track in?")
    key_input = input("  Key (C / C# / D / D# / E / F / F# / G / G# / A / A# / B): ").strip().upper()
    key = key_input if key_input in NOTE_MIDI else "F"
    if key != key_input:
        print(f"  Didn't catch that — defaulting to F (common trap key)")

    # Get genre context
    genre_input = input("  Genre (trap / drill / hip hop / rnb): ").strip().lower()
    genre = genre_input if genre_input in ["trap", "drill", "hip hop", "rnb"] else "trap"

    # Get problem
    print("\n  What's the problem?")
    for k, v in PROBLEMS.items():
        print(f"    {k}. {v}")
    prob_input = input("\n  Enter number (or press ENTER for full chain): ").strip()
    prob = prob_input if prob_input in PROBLEMS else "7"

    print(f"\n  Key   : {key}")
    print(f"  Genre : {genre}")
    print(f"  Issue : {PROBLEMS[prob]}")

    # Write guide
    guide_path = _write_808_guide(output_dir, key, genre, prob)
    print(f"\n  808 guide → {guide_path.name}")
    print("  Open it. Work top to bottom. Tune first — always.\n")


def _write_808_guide(output_dir: Path, key: str, genre: str, problem: str) -> Path:

    midi_note = NOTE_MIDI[key]
    freq_hz   = NOTE_HZ[key]

    # Build tuning reference — full octave range
    tuning_chart = _build_tuning_chart(key)

    # Sidechain settings by genre
    sidechain = {
        "trap":    {"duck": "-10 to -14 dB", "attack": "1ms",  "release": "120ms"},
        "drill":   {"duck": "-8 to -12 dB",  "attack": "1ms",  "release": "100ms"},
        "hip hop": {"duck": "-6 to -10 dB",  "attack": "5ms",  "release": "150ms"},
        "rnb":     {"duck": "-4 to -8 dB",   "attack": "10ms", "release": "200ms"},
    }.get(genre, {"duck": "-10 to -14 dB", "attack": "1ms", "release": "120ms"})

    content = f"""
================================================================================
  808 DIAL — {key} | {genre.upper()}
  Generated by: SAN3 Co-Producer
================================================================================

RULE #1: Tune before you mix. Everything else is wasted time if the 808 is off-key.

--------------------------------------------------------------------------------
STEP 1 — TUNING (Do this first. Every time.)
--------------------------------------------------------------------------------

  Your track is in: {key}
  Target frequency : {freq_hz} Hz
  MIDI note number : {midi_note} (standard) / shown as {key}5 in FL Studio

  HOW TO TUNE IN FL STUDIO:
    1. Load your 808 sample in the Channel Rack
    2. Right-click the Channel → "Pitch" knob — adjust until it matches
    3. Better method: Add "Pitcher" or "NewTone" plugin to the 808 mixer insert
       Set to note {key} — let it tell you how far off you are
    4. No pitch plugin? Use your ears + a tuner:
       Open the Mixer insert for the 808
       Add "Fruity Peak Controller" — watch for the fundamental frequency
       Solo the 808 and hum {key}. If they don't match — keep adjusting.

  OCTAVE CHECK:
    808s typically sit best at the 2nd or 3rd octave
    In FL Studio: {key}2 = deep sub, {key}3 = sub with presence, {key}4 = mid-heavy
    Start at {key}3 for trap. Go lower if you want more sub. Go higher if you want more click.

  TUNING REFERENCE — {key} ACROSS OCTAVES:
{tuning_chart}

--------------------------------------------------------------------------------
STEP 2 — FL STUDIO MIXER CHAIN (Top to bottom. In order.)
--------------------------------------------------------------------------------

  SLOT 1: Fruity Parametric EQ 2  (7-band EQ)
  ┌─────────────────────────────────────────────────────────────────┐
  │  Band 1 — High Pass Filter                                      │
  │    Type: High Pass | Freq: 28-32 Hz | Slope: Steep 4 (-24dB)   │
  │    Why: Remove subsonic rumble below musical content            │
  │                                                                 │
  │  Band 2 — Sub Boost (if 808 needs more boom)                    │
  │    Type: Low Shelf | Freq: 55-65 Hz | Gain: +2 to +4 dB        │
  │    Why: Add weight in the sub range                             │
  │                                                                 │
  │  Band 3 — Mud Cut (always apply)                                │
  │    Type: Peaking | Freq: 200-320 Hz | Gain: -4 to -7 dB        │
  │    BW: Moderate (Q ~1.5) | Why: Remove boxy mud                 │
  │                                                                 │
  │  Band 4 — Click/Presence Boost (for small speaker translation)  │
  │    Type: Peaking | Freq: 2-4 kHz | Gain: +2 to +3 dB           │
  │    BW: Wide (Q ~0.8) | Why: Makes 808 audible on phones/buds   │
  └─────────────────────────────────────────────────────────────────┘

  NOTE ON FL STUDIO 24: Use HQ+ mode on Parametric EQ 2 for
  more analog-style filter behavior. Right-click HQ button → HQ+

  SLOT 2: Fruity Compressor
  ┌─────────────────────────────────────────────────────────────────┐
  │  Attack    : 10-20 ms  (let transient through first)           │
  │  Release   : 150-250 ms (longer for smoother sustain)          │
  │  Threshold : -16 to -20 dB                                     │
  │  Ratio     : 3:1 to 4:1                                        │
  │  Makeup    : Add gain back to match uncompressed level          │
  │  Why: Control the tail, keep the slam, smooth the sustain      │
  └─────────────────────────────────────────────────────────────────┘

  OR — Use Maximus (multiband) for more control:
  ┌─────────────────────────────────────────────────────────────────┐
  │  LOW BAND (sub, 0-120hz):                                      │
  │    Threshold: -18 dB | Ratio: 4:1                              │
  │    Attack: 30ms | Release: 200ms                               │
  │    This controls the sub independently from the mids           │
  │                                                                 │
  │  MID BAND (120hz-5khz): Light or bypassed                      │
  │  HIGH BAND: Bypassed for 808                                   │
  └─────────────────────────────────────────────────────────────────┘

  SLOT 3: Fruity Fast Dist OR Soundgoodizer (Saturation)
  ┌─────────────────────────────────────────────────────────────────┐
  │  Fruity Fast Dist:                                              │
  │    Pre: 0.15 | Post: 0.85 | Mix: 20-30%                       │
  │    Type: Soft clip                                              │
  │                                                                 │
  │  Soundgoodizer: Mode A | Amount: 20-30%                        │
  │                                                                 │
  │  Why: Adds harmonic content (2nd/3rd harmonics) so the 808    │
  │  is audible on speakers that can't reproduce sub bass          │
  └─────────────────────────────────────────────────────────────────┘

  SLOT 4: Sidechain from Kick (CRITICAL — do not skip)
  ┌─────────────────────────────────────────────────────────────────┐
  │  METHOD (FL Studio native):                                     │
  │    1. Route your KICK to its own Mixer insert (e.g. Insert 2) │
  │    2. On the KICK insert, add "Fruity Peak Controller"         │
  │    3. Set Peak Controller: Base=0, Volume=100%, Attack=1ms,    │
  │       Release={sidechain["release"]}, Tension=0               │
  │    4. Right-click the 808's VOLUME knob in the Mixer           │
  │       → "Link to controller" → select the Peak Controller     │
  │    5. In the link dialog:                                       │
  │       Mapping: Inverted | Min: leave default | Max: 100%       │
  │                                                                 │
  │  Result: Kick ducks the 808 by {sidechain["duck"]}            │
  │  Attack: {sidechain["attack"]} | Release: {sidechain["release"]} │
  │                                                                 │
  │  Genre note ({genre}): You want the 808 to breathe back        │
  │  in fast enough that the sustain feels present between hits    │
  └─────────────────────────────────────────────────────────────────┘

--------------------------------------------------------------------------------
STEP 3 — MONO CHECK (Non-negotiable)
--------------------------------------------------------------------------------

  On your MASTER mixer channel:
    Add "Fruity Stereo Shaper" → set to MONO temporarily

  Your 808 should still be present and punchy in mono.

  If it disappears completely:
    → Too much sub, not enough 2-4 kHz presence
    → Go back to Slot 1, increase the click boost band

  If it sounds thin in mono but fine in stereo:
    → Your 808 may have stereo width applied — remove it
    → 808 and bass should be MONO. Always.

--------------------------------------------------------------------------------
STEP 4 — REFERENCE CHECK
--------------------------------------------------------------------------------

  Pull a reference track in the same key and genre.
  Load it as an audio clip in the Playlist.
  Route it to a Mixer insert.
  A/B your 808 against the reference.

  Ask:
    Does it sit in the same pocket? (volume-wise)
    Does it have the same weight? (frequency-wise)
    Does the kick and 808 complement each other?

  If your 808 is fighting the kick:
    → The kick and 808 are probably too close in frequency
    → Cut the kick at 60-80 Hz, let the 808 own that space
    → OR retune the kick to be slightly above the 808 root

================================================================================
  PROBLEM-SPECIFIC FIXES
================================================================================

  WEAK / NO BOOM:
    → Check octave: go down one octave (e.g., {key}3 → {key}2)
    → Boost Low Shelf @ 55hz by +4 dB in EQ
    → Check headroom — is your 808 channel too quiet in the mixer?

  MUDDY:
    → Cut 200-350hz harder (-6 to -9 dB)
    → High-pass at 35hz instead of 28hz
    → Check for buildup from other instruments in same range

  CLASHING WITH KICK:
    → They're probably both peaking at 60-80hz
    → EQ the KICK: boost 60-80hz, cut the 808 there slightly
    → Let each instrument own its frequency range

  OUT OF TUNE:
    → Start over from Step 1. Everything else is irrelevant if it's out of tune.
    → Use NewTone (FL Studio 20+) for sample pitch correction

  DISAPPEARS ON SMALL SPEAKERS:
    → Add more saturation (Slot 3): push to 35-40% mix
    → Boost 2-3 kHz by +4 dB
    → The sub is fine — you need upper harmonics for phone speakers

  TOO LOUD / DISTORTING:
    → Lower the channel volume in the Mixer (not the Channel Rack)
    → Set the Maximus ceiling to -1 dB on the LOW band
    → Check if the master is clipping — add headroom at the source

================================================================================
"""

    path = output_dir / f"808_dial_{key}_{genre.replace(' ', '_')}.txt"
    path.write_text(content.strip(), encoding="utf-8")
    return path


def _build_tuning_chart(root: str) -> str:
    """Build a reference chart showing the root note across octaves."""
    all_notes = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]
    root_idx  = all_notes.index(root)

    lines = []
    for octave in range(1, 6):
        midi = (octave + 1) * 12 + root_idx  # C1=24, C2=36...
        fl_octave = octave + 1  # FL Studio shows one octave higher
        lines.append(f"    {root}{octave} (FL Studio: {root}{fl_octave}) — MIDI {midi}")
    return "\n".join(lines)


if __name__ == "__main__":
    out = Path(__file__).parent.parent / "outputs"
    out.mkdir(exist_ok=True)
    run(out)
