# modes/beat_block.py
# SAN3 Producer — Beat Block Unlock Mode
# For: Hip Hop | RnB | Rap | Trap producers

from pathlib import Path
from midiutil import MIDIFile
import random

# --- SCALE DEFINITIONS ---
SCALES = {
    "minor":      [0, 2, 3, 5, 7, 8, 10],
    "minor_pent": [0, 3, 5, 7, 10],
    "chromatic":  [0, 2, 3, 5, 7, 8, 11],  # minor with raised 7 — dark, dramatic
    "dorian":     [0, 2, 3, 5, 7, 9, 10],  # minor with raised 6 — soulful
}

# MIDI root notes — C4 = 60 standard (shows as C5 in FL Studio)
NOTES = {
    "C":  60, "C#": 61, "D": 62, "D#": 63,
    "E":  64, "F":  65, "F#": 66, "G":  67,
    "G#": 68, "A":  69, "A#": 70, "B":  71,
}

# Genre presets — tightly scoped to the culture
GENRE_PRESETS = {
    "trap":     {"bpm": 140, "key": "F",  "scale": "minor",      "vibe": "dark, hard, Atlanta"},
    "drill":    {"bpm": 144, "key": "G#", "scale": "minor",      "vibe": "cold, minimal, menacing"},
    "hip hop":  {"bpm": 90,  "key": "A",  "scale": "minor_pent", "vibe": "grimy, soulful, 90s/boom bap"},
    "rap":      {"bpm": 95,  "key": "D",  "scale": "minor",      "vibe": "raw, aggressive, lyric-driven"},
    "rnb":      {"bpm": 85,  "key": "A#", "scale": "dorian",     "vibe": "smooth, emotional, sensual"},
    "melodic":  {"bpm": 140, "key": "C#", "scale": "minor",      "vibe": "melodic trap, emotional, cinematic"},
    "dark":     {"bpm": 135, "key": "G#", "scale": "chromatic",  "vibe": "horror, cinematic, menacing trap"},
    "bounce":   {"bpm": 100, "key": "G",  "scale": "minor_pent", "vibe": "club, energetic, Southern hip hop"},
}


def run(output_dir: Path) -> None:
    """Interactive beat block unlock session."""
    print("\n" + "="*52)
    print("  BEAT BLOCK — SAN3 Co-Producer")
    print("  Hip Hop | RnB | Rap | Trap")
    print("="*52)
    print("\nYou're stuck. We fix that right now.")
    print("Two questions. Answer or press ENTER to let me pick.\n")

    genre_input = input("  What you making? (trap / drill / hip hop / rap / rnb / melodic / dark / bounce): ").strip().lower()
    bpm_input   = input("  BPM? (press ENTER to use genre default): ").strip()

    # Resolve genre — default to trap if blank/unrecognized
    genre = _match_genre(genre_input)
    preset = GENRE_PRESETS[genre]

    # BPM — use input or default
    try:
        bpm = int(bpm_input) if bpm_input else preset["bpm"]
    except ValueError:
        bpm = preset["bpm"]

    key   = preset["key"]
    scale = preset["scale"]
    vibe  = preset["vibe"]

    print(f"\n  Genre : {genre.upper()}")
    print(f"  BPM   : {bpm}")
    print(f"  Key   : {key} {scale}")
    print(f"  Vibe  : {vibe}")

    # Write the ritual guide
    ritual_path = _write_ritual(output_dir, genre, bpm, key, scale, vibe)
    print(f"\n  Ritual guide → {ritual_path.name}")

    # Generate MIDI seed
    midi_path = _generate_seed_midi(output_dir, genre, bpm, key, scale)
    print(f"  MIDI seed     → {midi_path.name}")

    print("\n  Open FL Studio. Follow the ritual. Do NOT skip Step 1.")
    print("  You have everything you need to start.\n")


def _match_genre(raw: str) -> str:
    """Match user input to a genre preset. Default: trap."""
    for genre in GENRE_PRESETS:
        if genre in raw or raw in genre:
            return genre
    return "trap"


def _write_ritual(output_dir: Path, genre: str, bpm: int,
                  key: str, scale: str, vibe: str) -> Path:
    """Write the beat block unlock ritual as a plain text guide."""

    scale_note_names = _get_scale_note_names(key, scale)
    safe_genre = genre.replace(" ", "_")

    content = f"""
================================================================================
  BEAT BLOCK UNLOCK — {genre.upper()} | {bpm} BPM | {key} {scale.upper()}
  Vibe: {vibe}
  Generated by: SAN3 Co-Producer
================================================================================

You are not going to make a perfect beat right now.
You are going to make A beat. Imperfect. Moving. Real.

SCALE NOTES FOR THIS SESSION:
  {key} {scale}: {" — ".join(scale_note_names)}
  Use ONLY these notes. No exceptions until you have a loop.

--------------------------------------------------------------------------------
STEP 1 — ANCHOR THE DRUMS (5 minutes. Timer on.)
--------------------------------------------------------------------------------

  Open FL Studio. New project. Set BPM to {bpm}.

  Open the Step Sequencer. Create a pattern called "DRUMS_01".

  KICK placement:
    Step 1 (beat 1) — always
    Step 9 (beat 3) — always
    Add 1 extra kick on step 11 or 13 for pocket (try both)

  SNARE / CLAP:
    Step 5 (beat 2) and Step 13 (beat 4) — locked
    Ghost snare: add step 15 at velocity 35-45

  HI-HAT (closed):
    Every even step (2, 4, 6, 8, 10, 12, 14, 16)
    Velocity: alternate 90 and 65 for groove
    Steps 7 and 15: velocity 100 (accent)

  DO NOT touch samples right now. Use any placeholder.
  If it grooves on the first loop — you're already past the block.

--------------------------------------------------------------------------------
STEP 2 — THE 808 ANCHOR (5 minutes.)
--------------------------------------------------------------------------------

  New pattern: "808_01"
  Open Piano Roll.

  ONE note. Root note of the key: {key}
  In FL Studio this is shown as {key}4 or {key}5 depending on your octave display.
  Length: 2 beats (half a bar).

  Settings on your 808 channel:
    Portamento (SLD): ON
    Slide time: 65ms
    Cut group: Set to group 1 so 808 chokes itself on new notes

  You are not writing a melody. You are writing a pulse.
  One root note. Looped. That is enough for now.

  Tune check: Solo the 808. Hum the root note out loud.
  If it matches → good. If not → adjust the pitch knob until it does.

--------------------------------------------------------------------------------
STEP 3 — THE HOOK SEED (10 minutes. No more.)
--------------------------------------------------------------------------------

  New pattern: "HOOK_01"
  Piano Roll. Scale: {key} {scale}

  Available notes this session:
    {chr(10).join(f"    {n}" for n in scale_note_names)}

  Rules:
    4 notes maximum for the first loop
    Start on or near {key} (the root)
    End on a note that feels unresolved — it makes the loop want to repeat
    Length: 2 bars

  Import the MIDI seed file for inspiration:
    File: midi_seed_{safe_genre}_{bpm}bpm_{key}.mid
    Right-click Piano Roll → Import MIDI → select the file above
    This is a starting point. Change it. It's yours.

  Ask yourself after 4 loops: Is this infectious?
    YES → You have a session. Build from here.
    NO  → Change ONE note. Loop again. Repeat this once.

--------------------------------------------------------------------------------
THE RULE
--------------------------------------------------------------------------------

  You now have:
    ✓ Drums
    ✓ 808 anchor
    ✓ Hook seed

  That is a beat. Everything else is arrangement and refinement.
  Do not start over. Build on what you have.

  Next session: Run SAN3 808_DIAL mode to dial in your 808 mix.

================================================================================
"""

    path = output_dir / f"beat_block_{safe_genre}_{bpm}bpm_{key}.txt"
    path.write_text(content.strip(), encoding="utf-8")
    return path


def _generate_seed_midi(output_dir: Path, genre: str,
                        bpm: int, key: str, scale: str) -> Path:
    """Generate a 4-bar MIDI seed pattern in the given key and scale."""

    root = NOTES.get(key, 60)
    intervals = SCALES.get(scale, SCALES["minor"])
    scale_notes = [root + i for i in intervals]
    scale_notes += [root + 12]  # add octave root

    midi = MIDIFile(1)
    midi.addTempo(0, 0, bpm)
    midi.addTimeSignature(0, 0, 4, 2, 24)

    track, channel = 0, 0

    # Build a genre-appropriate seed pattern
    patterns = {
        "trap":    _pattern_trap,
        "drill":   _pattern_drill,
        "hip hop": _pattern_hiphop,
        "rap":     _pattern_hiphop,
        "rnb":     _pattern_rnb,
        "melodic": _pattern_melodic,
        "dark":    _pattern_dark,
        "bounce":  _pattern_hiphop,
    }

    pattern_fn = patterns.get(genre, _pattern_trap)
    notes = pattern_fn(scale_notes)

    for (start, pitch, duration, velocity) in notes:
        midi.addNote(track, channel, pitch, start, duration, velocity)

    safe_genre = genre.replace(" ", "_")
    path = output_dir / f"midi_seed_{safe_genre}_{bpm}bpm_{key}.mid"
    with open(path, "wb") as f:
        midi.writeFile(f)
    return path


# --- GENRE MIDI PATTERNS ---

def _pattern_trap(scale_notes: list) -> list:
    """Sparse, dark, syncopated trap hook."""
    s = scale_notes
    return [
        (0.0,  s[4], 0.5,  95),
        (0.5,  s[2], 0.25, 80),
        (1.0,  s[0], 1.0,  100),
        (2.0,  s[3], 0.5,  85),
        (2.75, s[1], 0.25, 70),
        (3.0,  s[4], 1.0,  90),
        # bar 2
        (4.0,  s[2], 0.5,  90),
        (4.5,  s[0], 1.5,  100),
        (6.0,  s[6], 0.5,  80),
        (6.5,  s[4], 0.5,  85),
        (7.0,  s[0], 1.0,  95),
    ]

def _pattern_drill(scale_notes: list) -> list:
    """Cold, minimal, repeating drill riff."""
    s = scale_notes
    return [
        (0.0,  s[0], 0.25, 90),
        (0.25, s[0], 0.25, 75),
        (0.75, s[2], 0.5,  95),
        (1.5,  s[3], 0.25, 85),
        (2.0,  s[0], 0.25, 90),
        (2.25, s[0], 0.25, 70),
        (2.75, s[4], 0.5,  100),
        (3.5,  s[2], 0.5,  80),
        # bar 2 variation
        (4.0,  s[0], 0.25, 90),
        (4.25, s[0], 0.25, 75),
        (4.75, s[2], 0.5,  95),
        (5.5,  s[6], 0.25, 80),
        (6.0,  s[4], 1.0,  95),
        (7.0,  s[3], 0.5,  85),
        (7.5,  s[0], 0.5,  90),
    ]

def _pattern_hiphop(scale_notes: list) -> list:
    """Soulful, melodic boom bap / hip hop hook."""
    s = scale_notes
    return [
        (0.0,  s[4], 1.0,  90),
        (1.0,  s[5], 0.5,  85),
        (1.5,  s[4], 0.5,  80),
        (2.0,  s[2], 1.0,  95),
        (3.0,  s[0], 1.0,  100),
        (4.0,  s[3], 0.75, 85),
        (4.75, s[4], 0.25, 75),
        (5.0,  s[5], 1.0,  90),
        (6.0,  s[4], 0.5,  85),
        (6.5,  s[2], 0.5,  80),
        (7.0,  s[0], 1.0,  100),
    ]

def _pattern_rnb(scale_notes: list) -> list:
    """Smooth, emotional RnB with breath between notes."""
    s = scale_notes
    return [
        (0.0,  s[2], 0.75, 85),
        (1.0,  s[4], 1.0,  90),
        (2.25, s[5], 0.5,  80),
        (3.0,  s[4], 1.0,  95),
        (4.0,  s[2], 0.5,  85),
        (4.75, s[0], 1.5,  100),
        (6.5,  s[3], 0.5,  75),
        (7.0,  s[2], 1.0,  90),
    ]

def _pattern_melodic(scale_notes: list) -> list:
    """Melodic trap — emotional, flowing, cinematic."""
    s = scale_notes
    return [
        (0.0,  s[7], 0.5,  95),
        (0.5,  s[6], 0.5,  85),
        (1.0,  s[4], 1.0,  100),
        (2.0,  s[5], 0.5,  90),
        (2.5,  s[4], 0.5,  80),
        (3.0,  s[2], 1.0,  95),
        (4.0,  s[4], 0.5,  90),
        (4.5,  s[2], 0.5,  85),
        (5.0,  s[0], 2.0,  100),
        (7.0,  s[2], 0.5,  70),
        (7.5,  s[4], 0.5,  80),
    ]

def _pattern_dark(scale_notes: list) -> list:
    """Dark, horror trap. Chromatic tension. Minimal movement."""
    s = scale_notes
    return [
        (0.0,  s[0], 1.0,  100),
        (1.0,  s[1], 0.5,  85),
        (1.75, s[0], 0.25, 70),
        (2.25, s[6], 0.75, 95),
        (3.0,  s[0], 1.0,  100),
        (4.0,  s[5], 0.5,  90),
        (4.75, s[4], 0.25, 75),
        (5.25, s[6], 0.75, 95),
        (6.0,  s[0], 0.5,  100),
        (6.5,  s[1], 0.5,  80),
        (7.0,  s[0], 1.0,  100),
    ]


def _get_scale_note_names(root_name: str, scale: str) -> list:
    """Return human-readable note names for the scale."""
    all_notes = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]
    root_idx = all_notes.index(root_name)
    intervals = SCALES.get(scale, SCALES["minor"])
    return [all_notes[(root_idx + i) % 12] for i in intervals]


if __name__ == "__main__":
    # Quick test
    out = Path(__file__).parent.parent / "outputs"
    out.mkdir(exist_ok=True)
    run(out)
