# modes/mix_chain.py
# SAN3 Producer — Mix Chain Mode
# For: Hip Hop | RnB | Rap | Trap producers

from pathlib import Path

GENRES = {
    "trap":    {"low_end": "heavy", "vibe": "punchy and hard", "master_ceiling": "-0.5"},
    "drill":   {"low_end": "heavy", "vibe": "cold and dry",   "master_ceiling": "-0.5"},
    "hip hop": {"low_end": "medium","vibe": "warm and punchy","master_ceiling": "-1.0"},
    "rnb":     {"low_end": "medium","vibe": "smooth and warm","master_ceiling": "-1.0"},
    "melodic": {"low_end": "heavy", "vibe": "emotional and cinematic", "master_ceiling": "-0.5"},
}

PROBLEMS = {
    "1": "Track sounds muddy / too much bass",
    "2": "Track sounds thin / no weight",
    "3": "Mix sounds amateur / elements fighting",
    "4": "Nothing sits together / no glue",
    "5": "Needs to be louder / not competitive",
    "6": "Full mix chain — start to finish",
}


def run(output_dir: Path) -> None:
    print("\n" + "="*52)
    print("  MIX CHAIN — SAN3 Co-Producer")
    print("  Hip Hop | RnB | Rap | Trap")
    print("="*52)

    genre_in = input("\n  Genre (trap / drill / hip hop / rnb / melodic): ").strip().lower()
    genre = _match_genre(genre_in)

    print("\n  What's the issue?")
    for k, v in PROBLEMS.items():
        print(f"    {k}. {v}")
    prob_in = input("\n  Choice (ENTER for full chain): ").strip()
    prob = prob_in if prob_in in PROBLEMS else "6"

    print(f"\n  Genre  : {genre.upper()}")
    print(f"  Issue  : {PROBLEMS[prob]}")

    guide_path = _write_mix_guide(output_dir, genre, prob)
    print(f"\n  Mix guide → {guide_path.name}")
    print("  Work through it channel by channel. Don't skip steps.\n")


def _match_genre(raw: str) -> str:
    for g in GENRES:
        if raw in g or g in raw:
            return g
    return "trap"


def _write_mix_guide(output_dir: Path, genre: str, problem: str) -> Path:
    g = GENRES[genre]

    problem_fixes = {
        "1": _fix_muddy(),
        "2": _fix_thin(),
        "3": _fix_fighting(),
        "4": _fix_glue(),
        "5": _fix_loudness(g["master_ceiling"]),
    }

    specific_fix = ""
    if problem != "6":
        specific_fix = f"""
================================================================================
  TARGETED FIX: {PROBLEMS[problem].upper()}
================================================================================

{problem_fixes.get(problem, "")}
"""

    content = f"""
================================================================================
  MIX CHAIN — {genre.upper()}
  Vibe: {g['vibe'].title()} | Low End: {g['low_end'].title()}
  Generated by: SAN3 Co-Producer
================================================================================

MINDSET BEFORE YOU START:
  Mix at low volume. Your ears make better decisions at 70-75 dB.
  Check mono frequently. If it sounds good in mono, it's a real mix.
  Reference constantly. Pull a professional track in the same key/genre.
  Gain stage first. Every channel should peak around -12 to -6 dBFS before any plugins.
{specific_fix}
================================================================================
  CHANNEL-BY-CHANNEL CHAIN (FL Studio Native Plugins)
================================================================================

────────────────────────────────────────
KICK DRUM — Insert Channel
────────────────────────────────────────

  SLOT 1: Fruity Parametric EQ 2
    Band 1 — High Pass:  40 Hz | Steep 4 | Remove sub rumble
    Band 2 — Boost:      60-80 Hz | +2 to +3 dB | Low Shelf | Add boom
    Band 3 — Cut:        300-500 Hz | -4 to -6 dB | Peaking | Remove boxiness
    Band 4 — Boost:      3-5 kHz | +3 to +4 dB | Peaking | Add click/attack
    Band 5 — Air:        10 kHz | +1 dB | High Shelf | Presence

  SLOT 2: Fruity Compressor
    Attack:    5 ms    (fast — catch the peak)
    Release:   60 ms   (tight — let it breathe)
    Threshold: -18 dB
    Ratio:     4:1
    Makeup:    +3-4 dB (match pre-comp volume)
    Mode:      Peak

  SLOT 3: Fruity Fast Dist (optional — adds punch)
    Pre: 0.2 | Post: 0.8 | Type: Fast | Mix: 15-20%

  NOTES:
    The kick owns 60-80 Hz. Cut everything else there.
    Sidechain your 808 FROM this kick channel (see 808 Dial mode).
    Keep the kick channel MONO (no stereo width).

────────────────────────────────────────
808 / SUB BASS — Insert Channel
────────────────────────────────────────

  → See 808 DIAL MODE for complete chain.
  Key reminders here:
    Tune it to the key before touching anything else.
    It must be MONO. Zero stereo width on this channel.
    Sidechain it from the kick (6-12 dB duck, 120ms release).
    Run it through saturation for phone speaker translation.

────────────────────────────────────────
SNARE / CLAP — Insert Channel
────────────────────────────────────────

  SLOT 1: Fruity Parametric EQ 2
    Band 1 — High Pass:  150 Hz | Remove mud
    Band 2 — Body:       200-250 Hz | +2 dB | Peaking | Add thump
    Band 3 — Cut:        700 Hz-1 kHz | -3 dB | Remove honk
    Band 4 — Crack:      6-8 kHz | +3 to +4 dB | Peaking | Attack
    Band 5 — Air:        12 kHz | +2 dB | High Shelf | Crispness

  SLOT 2: Fruity Compressor
    Attack:    10 ms   (let transient breathe first)
    Release:   80 ms
    Threshold: -16 dB
    Ratio:     3:1

  SLOT 3: Fruity Reverb 2
    Room size:  20-25%
    Decay:      0.3-0.5s (trap — keep it short and dry)
    High damp:  60%     (dark room, not bright)
    Mix:        12-18%
    Pre-delay:  8-12ms  (pushes snare forward in the mix)

  NOTES:
    Stack clap + snare. Clap adds width, snare adds body.
    Phase check: if they cancel each other when stacked, flip phase on one.
    Trap snare should be slightly wide. Boom bap snare can be mono.

────────────────────────────────────────
HI-HATS — Insert Channel (all hats together)
────────────────────────────────────────

  SLOT 1: Fruity Parametric EQ 2
    Band 1 — High Pass:  5-8 kHz | Remove anything below — hats live up top
    Band 2 — Air cut:    16 kHz | -2 dB | Gentle | Remove harshness
    Band 3 — Presence:   10 kHz | +1 to +2 dB | Peaking | Clarity

  SLOT 2: Fruity Compressor (optional — only if hats are inconsistent)
    Attack:    1 ms
    Release:   40 ms
    Threshold: -12 dB
    Ratio:     2:1

  SLOT 3: Fruity Stereo Enhancer
    Width: 60-80%
    Why: Hats should sit wide, creating space for the kick/808 in the center

  NOTES:
    Hats should NOT be the loudest element. They sit in the background.
    If they're harsh: cut 8-10 kHz slightly.
    If they're dull: boost 12-14 kHz slightly.

────────────────────────────────────────
MELODY / LEAD SYNTH — Insert Channel
────────────────────────────────────────

  SLOT 1: Fruity Parametric EQ 2
    Band 1 — High Pass:  200-300 Hz | Clean the sub from the melody
    Band 2 — Mud cut:    400-600 Hz | -2 to -3 dB | Peaking | Remove mud
    Band 3 — Presence:   2-4 kHz | +2 dB | Peaking | Push it forward
    Band 4 — Air:        12-16 kHz | +2 dB | High Shelf | Shimmer

  SLOT 2: Fruity Stereo Enhancer
    Width: 50-70%
    Why: Melody sits wide — creates space for vocals in the center

  SLOT 3: Fruity Delay 3
    Delay time: 1/8 note (sync to BPM)
    Feedback:   25-30%
    Cut high:   5 kHz (so delays don't clutter)
    Mix:        15-20%

  SLOT 4: Fruity Reverb 2
    Room size:  35-40%
    Decay:      1.0-1.5s
    Pre-delay:  15-20ms
    High damp:  40%
    Mix:        20-25%

  NOTES:
    The melody and kick/808 should never be in the same frequency space.
    HPF at 200-300 Hz ensures the melody doesn't muddy your low end.
    For RnB: more reverb, longer pre-delay. For trap: shorter, drier.

────────────────────────────────────────
PAD / ATMOSPHERE — Insert Channel
────────────────────────────────────────

  SLOT 1: Fruity Parametric EQ 2
    High Pass: 300-400 Hz | Cut all low end
    Low Pass:  8-10 kHz  | Cut harsh highs

  SLOT 2: Fruity Reverb 2
    Room size: 60-70% | Decay: 2-3s | Mix: 40-60%
    This element IS the room. Let it breathe.

  SLOT 3: Fruity Stereo Enhancer
    Width: 80-100%
    Pads should fill the entire stereo field

  NOTES:
    Pads should be LOW in the mix. They create depth, not presence.
    Automate the volume to duck slightly during the hook.

────────────────────────────────────────
VOCALS — Insert Channel (if applicable)
────────────────────────────────────────

  SLOT 1: Fruity Parametric EQ 2
    High Pass: 80-100 Hz | Remove rumble and breath
    Cut:       200-400 Hz | -3 to -4 dB | Remove mud/boxiness
    Presence:  3-5 kHz | +2 to +3 dB | Intelligibility
    Air:       12-16 kHz | +2 dB | Clarity

  SLOT 2: Fruity Compressor
    Attack:    15-20 ms  (let vocal transient through)
    Release:   100-150 ms
    Threshold: -18 to -22 dB
    Ratio:     3:1 to 4:1
    Makeup:    match original level

  SLOT 3: Fruity Delay 3
    Ping-pong delay: 1/8 dotted (triplet feel)
    Feedback: 20%
    Mix: 15%

  SLOT 4: Fruity Reverb 2
    Room size: 20-30% | Decay: 0.8-1.2s | Mix: 20-25%

================================================================================
  MASTER BUS — Mixer Channel 1
================================================================================

  SLOT 1: Fruity Parametric EQ 2 (master EQ)
    Sub cut:    25-30 Hz | High Pass | Remove inaudible sub rumble
    Low cut:    45 Hz    | High Pass | Keep only musical sub bass
    Air boost:  12 kHz   | +1 to +1.5 dB | High Shelf | Open the mix
    Cut check:  500 Hz   | Solo this range — if something is harsh, cut here

  SLOT 2: Maximus (master limiter/maximizer)
    Master section:
      Threshold: -3 to -4 dB
      Ceiling: {g["master_ceiling"]} dBFS
      Attack: 10ms | Release: 200ms

    Low band (0-120 Hz):
      Threshold: -12 dB | Ratio: 2:1 | Controls sub without touching mids
    Mid band: Light compression only — don't over-squeeze the mids
    High band: Bypass or very light (+1-2 dB boost if needed)

  SLOT 3: Fruity Peak Meter (last in chain)
    Monitor: Never exceed {g["master_ceiling"]} dBFS on peaks
    Watch for: consistent level, not jumping between -12 and -0.5

  FINAL MONO CHECK:
    Add Fruity Stereo Shaper on master → set to MONO
    Your mix should still punch in mono.
    If the 808 disappears: needs more saturation / upper harmonics
    If the kick disappears: needs more click (3-5 kHz presence)

================================================================================
  MIX ORDER CHECKLIST
================================================================================

  □ 1. Gain stage all channels (-12 to -6 dBFS average, nothing clipping)
  □ 2. Set relative volumes (rough balance — no plugins yet)
  □ 3. Process kick and 808 first (they define everything else)
  □ 4. Set up sidechain (kick → 808 duck)
  □ 5. Process snare/clap
  □ 6. Process hi-hats
  □ 7. EQ and space melody / lead
  □ 8. Add depth with reverb and delay
  □ 9. Check stereo width (center: kick/808/vocals, sides: hats/melody/pads)
  □ 10. Master bus processing — last
  □ 11. Mono check
  □ 12. Reference check against professional track

================================================================================
"""

    safe = genre.replace(" ", "_")
    path = output_dir / f"mix_chain_{safe}.txt"
    path.write_text(content.strip(), encoding="utf-8")
    return path


def _fix_muddy() -> str:
    return """  THE PROBLEM: Too much energy in the 200-400 Hz range.
  Everything is fighting in the same space.

  FIX IT:
    1. Solo each channel. Find what's causing the mud (usually 808, kick, or melody stacked).
    2. On EVERY channel except the 808/kick: High Pass at minimum 200 Hz.
    3. On the 808: Cut 200-350 Hz by -5 to -7 dB (Parametric EQ 2, Peaking, narrow Q).
    4. On the melody: High Pass at 300 Hz.
    5. On the pad: High Pass at 400 Hz.
    6. Check master: If still muddy, cut master EQ at 250 Hz by -2 dB.

  RULE: Only the kick and 808 live below 200 Hz. Everything else gets cut there."""


def _fix_thin() -> str:
    return """  THE PROBLEM: Mix has no weight or body.
  Usually means the low end is missing or the 808 isn't hitting.

  FIX IT:
    1. Check 808 tuning first. If it's out of key, it won't hit no matter what.
    2. Check 808 volume in the mixer — it should be the 2nd loudest element after the kick.
    3. Add Low Shelf boost on 808: +3 to +4 dB at 60-70 Hz.
    4. Check for High Pass filters set too high — don't cut below 30 Hz on the 808.
    5. Add saturation to the 808 (Fruity Fast Dist, Mix 25%) for upper harmonics.
    6. Kick: boost 60-80 Hz by +2 to +3 dB for more boom.
    7. Check mono — does it hit in mono? If yes, it's fine. Keep building."""


def _fix_fighting() -> str:
    return """  THE PROBLEM: Elements are competing. Nothing has its own space.
  The mix sounds busy and unfocused.

  FIX IT — FREQUENCY SEPARATION:
    Kick:    owns 60-80 Hz. Cut everything else there.
    808:     owns 40-120 Hz. Sits just under and with the kick.
    Snare:   owns 200 Hz (body) + 6-8 kHz (crack). Cut 300-500 Hz.
    Melody:  owns 300 Hz-4 kHz. High pass at 300 Hz.
    Hats:    own 5 kHz+. High pass at 5 kHz.
    Pad:     owns the reverb space. Keep it LOW in the mix. Width: wide.

  RULE: If two elements occupy the same frequency range, one of them needs to move.
  Usually you cut the less important one and boost the important one."""


def _fix_glue() -> str:
    return """  THE PROBLEM: Mix sounds like separate sounds, not a track.
  Elements don't sit together.

  FIX IT:
    1. Light master bus compression (Maximus): Ratio 1.5:1, Threshold -6 dB.
       This adds glue without squashing.
    2. Add a ROOM reverb send:
       Create a new Mixer channel labeled "ROOM"
       Add Fruity Reverb 2: Room 30%, Decay 0.6s, Mix 100%
       Send every channel 5-15% to this room bus
       This puts all elements in the same acoustic space.
    3. Parallel compression on drums:
       Send kick/snare to a bus
       Compress hard: Ratio 8:1, Threshold -20 dB
       Blend back at 20-30% — adds density and punch
    4. Low pass the reverb return at 8 kHz (so only low-mid reverb feeds back)"""


def _fix_loudness(ceiling: str) -> str:
    return f"""  THE PROBLEM: Mix isn't loud enough. Sounds quiet next to reference tracks.

  FIX IT — PROPER LOUDNESS CHAIN:
    1. Check gain staging FIRST. If channels are peaking above -6 dBFS,
       turn them down. You can't add loudness to a distorted source.
    2. High Pass EVERYTHING that doesn't need sub. Sub frequencies eat headroom.
       Cut everything below 30 Hz on the master bus.
    3. Maximus settings for loudness:
       Master: Threshold -3 dB | Ceiling: {ceiling} dBFS | Attack: 5ms | Release: 150ms
       Low band: Threshold -10 dB | Ratio 2:1 | Controls sub separately
    4. After Maximus: add Fruity Limiter as a final safety net:
       Ceiling: {ceiling} dBFS | Release: Auto
    5. Target LUFS: -9 to -11 LUFS integrated for streaming.
       Use Fruity Peak Meter extended view or a LUFS meter plugin.

  REMEMBER: Loudness comes from a balanced, clean mix first.
  Maximus can only do its job if the mix underneath is solid."""


if __name__ == "__main__":
    out = Path(__file__).parent.parent / "outputs"
    out.mkdir(exist_ok=True)
    run(out)
